### PR TITLE
Update architecture.md

### PR DESCRIPTION
**Pull request by BallOfDestruction**
* Fixed declination and translate mistakes.
* Made sometimes a text more comfortable for reading in Russian

### CODE REVIEW

**Comment by v-elcou** [comment]
Hello @BallOfDestruction, 
Thank for your contribution. We are currently reviewing and will communicate the decision taken. 
Thanks for your time and support on this.

Kind regards,
Microsoft C&E Localization Team

**Comment by ticianaciminari** [comment]
@BallOfDestruction:
Can you please sign CLA so that we can merge the PR?
Kind regards,
Microsoft C&E Localization Team

**Comment by ticianaciminari** [comment]
@BallOfDestruction:
Can you please sign CLA so that we can merge the PR?
Kind regards,
Microsoft C&E Localization Team

**Comment by BallOfDestruction** [comment]
Sorry for late, dear Ticiana

Kind regards,
Vakhtin Alexandr

**Pull request merged**
